import = [
#"~/.config/alacritty/gruvbox.toml",
"~/.config/alacritty/windows.toml",
"~/.config/alacritty/font.toml",
"~/.config/alacritty/cursor.toml",
"~/.config/alacritty/catppuchin-mocha.toml"
]

[env]
TERM = "xterm-256color"


