import = [
"~/.config/alacritty/gruvbox.toml",
]

[env]
TERM = "xterm-256color"

[window]
title= "Alacritty"
dynamic_title = false
dimensions = { columns = 150, lines = 30}
resize_increments = true

# Font configuration
[font]
  # Regular font
  normal = {family = "Source Code Pro", style = "regular"}
  # Bold font face
  bold = {family = "Source Code Pro", style = "Bold"}
  # Italic font face
  italic = {family = "Source Code Pro", style = "Italic"}
  # Bold italic font face
  bold_italic = {family = "Source Code Pro", style = "Bold Italic"}
  # Point size
  size = 10.0
  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset = {x = 0, y = 1}
  #draw_bold_text_with_bright_colors= true
